### PR TITLE
fix(indent-binary-ops): indent on multiline assignment

### LINKED ISSUE #546: `indent-binary-ops`: Expects 0 intendation on multiline re-assignment
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I noticed that the indentation of the multiline assignment depends on whether it is an assignment (line starts with `const` or `let`) or an re-assignment (line starts just with the variable itself).

Expected:

```ts
const a = 1
  + 2;

let b = 1
  + 2;

b = 2
  + 2; // expected
```

Actual:

```ts
const a = 1
  + 2;

let b = 1
  + 2;

b = 2
+ 2; // actual
```

### Reproduction

https://stackblitz.com/edit/github-fmnurc?file=src%2Findex.ts,README.md,eslint.config.js

### Contributes

- ~~[ ] I am willing to submit a PR to fix this issue~~
- ~~[ ] I am willing to submit a PR with failing tests~~

### PR DESCRIPTION
**Pull request by 9romise**
### Description

Fixes cases about assignment in https://github.com/eslint-stylistic/eslint-stylistic/issues/226#issuecomment-2208529955

### Linked Issues

fixes #546

### CODE REVIEW

File: packages/eslint-plugin/rules/array-bracket-spacing/array-bracket-spacing._js_.ts [hunk 1]
```diff
@@ -188,14 +188,14 @@ export default createRule<RuleOptions, MessageIds>({
 
       const openingBracketMustBeSpaced
                 = firstElement && options.objectsInArraysException && isObjectType(firstElement)
-                || firstElement && options.arraysInArraysException && isArrayType(firstElement)
-                || options.singleElementException && node.elements.length === 1
+                  || firstElement && options.arraysInArraysException && isArrayType(firstElement)
+                  || options.singleElementException && node.elements.length === 1
                   ? !options.spaced : options.spaced
```
Comment (9romise) [inline packages/eslint-plugin/rules/array-bracket-spacing/array-bracket-spacing._js_.ts:193]: looks like something breaks in `indent` here

Comment (9romise) [reply packages/eslint-plugin/rules/array-bracket-spacing/array-bracket-spacing._js_.ts:193]: oh! I see, it is correct. The ternary expression's condition is the whole multi-line logical expression.
